from typing import List, Dict, Any

RULES_CATALOG: List[Dict[str, Any]] = [
    # --- Authentication & Password Security ---
    {
        "rule_code": "SEC-AUTH-001",
        "title": "Enable Password Encryption / Hashing",
        "category": "Authentication",
        "vendor": "cisco",
        "default_severity": "CRITICAL",
        "description": "Ensure global service password-encryption or secret hashing (Type 8/9/secret 5) is enabled to prevent plaintext password exposure.",
        "pass_pattern": r"(service password-encryption|enable secret \d|username .* secret \d)",
        "fail_pattern": r"(no service password-encryption|enable password [^\d]|username .* password [^\d])",
        "remediation_guidance": "Enable global password encryption:\n  (config)# service password-encryption\nReplace unhashed passwords with secret 8 or 9:\n  (config)# enable secret <strong-password>",
        "cis_mapping": "CIS Cisco IOS Benchmark 1.1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 IA-5(1)",
        "stig_mapping": "DISA STIG NET-0410",
        "iso_mapping": "ISO 27001:2022 A.9.4.3"
    },
    {
        "rule_code": "SEC-AUTH-002",
        "title": "AAA Authentication Model Enabled",
        "category": "Authentication",
        "vendor": "cisco",
        "default_severity": "HIGH",
        "description": "Ensure AAA new-model is enabled for centralized authentication, authorization, and accounting.",
        "pass_pattern": r"aaa new-model",
        "fail_pattern": r"no aaa new-model",
        "remediation_guidance": "Enable AAA new-model:\n  (config)# aaa new-model\n  (config)# aaa authentication login default local group radius",
        "cis_mapping": "CIS Cisco IOS Benchmark 1.2.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-2, IA-2",
        "stig_mapping": "DISA STIG NET-0420",
        "iso_mapping": "ISO 27001:2022 A.9.2.1"
    },
    {
        "rule_code": "SEC-AUTH-003",
        "title": "Encrypted Root Authentication (Junos)",
        "category": "Authentication",
        "vendor": "junos",
        "default_severity": "CRITICAL",
        "description": "Ensure Junos root authentication uses SHA-512 or AES encrypted password hash.",
        "pass_pattern": r"(root-authentication.*encrypted-password|encrypted-password \"\$6\$)",
        "fail_pattern": r"(root-authentication.*plain-text-password|plain-text-password-password)",
        "remediation_guidance": "Configure encrypted root password in Junos:\n  set system root-authentication plain-text-password",
        "cis_mapping": "CIS Juniper Junos Benchmark 1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 IA-5(2)",
        "stig_mapping": "DISA STIG JUN-0010",
        "iso_mapping": "ISO 27001:2022 A.9.4.3"
    },
    {
        "rule_code": "SEC-AUTH-004",
        "title": "FortiOS Admin Password Hashing",
        "category": "Authentication",
        "vendor": "fortios",
        "default_severity": "HIGH",
        "description": "Ensure FortiOS admin accounts do not use default or plaintext passwords.",
        "pass_pattern": r"set password ENC",
        "fail_pattern": r"set password [^E][^N][^C]",
        "remediation_guidance": "Set secure encrypted password for admin in FortiOS:\n  config system admin\n    edit admin\n      set password <strong-password>\n  end",
        "cis_mapping": "CIS Fortinet FortiOS Benchmark 1.2 (L1)",
        "nist_mapping": "NIST SP 800-53 IA-5",
        "stig_mapping": "DISA STIG FGT-0015",
        "iso_mapping": "ISO 27001:2022 A.9.4.3"
    },

    # --- Remote Access & SSH Security ---
    {
        "rule_code": "SEC-RMT-001",
        "title": "Enforce SSH Version 2 Only",
        "category": "Remote Access",
        "vendor": "cisco",
        "default_severity": "CRITICAL",
        "description": "Ensure SSH version 2 is explicitly configured and legacy SSH v1 is disabled.",
        "pass_pattern": r"ip ssh version 2",
        "fail_pattern": r"(ip ssh version 1|no ip ssh version 2)",
        "remediation_guidance": "Enforce SSH v2:\n  (config)# ip ssh version 2\n  (config)# ip domain-name company.local\n  (config)# crypto key generate rsa modulus 2048",
        "cis_mapping": "CIS Cisco IOS Benchmark 2.1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-17, IA-5",
        "stig_mapping": "DISA STIG NET-0600",
        "iso_mapping": "ISO 27001:2022 A.13.1.1"
    },
    {
        "rule_code": "SEC-RMT-002",
        "title": "Disable Unencrypted Telnet Access",
        "category": "Remote Access",
        "vendor": "cisco",
        "default_severity": "CRITICAL",
        "description": "Ensure VTY transport input excludes Telnet and restricts incoming connections to SSH only.",
        "pass_pattern": r"transport input ssh",
        "fail_pattern": r"(transport input telnet|transport input all|transport input telnet ssh)",
        "remediation_guidance": "Disable Telnet on VTY lines:\n  (config)# line vty 0 15\n  (config-line)# transport input ssh",
        "cis_mapping": "CIS Cisco IOS Benchmark 2.1.2 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-17(2)",
        "stig_mapping": "DISA STIG NET-0610",
        "iso_mapping": "ISO 27001:2022 A.13.1.2"
    },
    {
        "rule_code": "SEC-RMT-003",
        "title": "Disable Insecure HTTP Management (FortiOS)",
        "category": "Remote Access",
        "vendor": "fortios",
        "default_severity": "HIGH",
        "description": "Disable HTTP administrative access on management interfaces and restrict to HTTPS.",
        "pass_pattern": r"set allowaccess .*https.*",
        "fail_pattern": r"set allowaccess .*http\b.*",
        "remediation_guidance": "Remove HTTP from interface allowaccess:\n  config system interface\n    edit mgmt\n      set allowaccess https ssh ping\n  end",
        "cis_mapping": "CIS Fortinet FortiOS Benchmark 2.1.3 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-17(1)",
        "stig_mapping": "DISA STIG FGT-0050",
        "iso_mapping": "ISO 27001:2022 A.13.1.1"
    },
    {
        "rule_code": "SEC-RMT-004",
        "title": "Restrict Junos SSH Protocol and Root Login",
        "category": "Remote Access",
        "vendor": "junos",
        "default_severity": "HIGH",
        "description": "Restrict SSH root login and mandate SSH v2 in Junos system services.",
        "pass_pattern": r"(system services ssh protocol-version v2|system services ssh root-login deny)",
        "fail_pattern": r"system services ssh root-login allow",
        "remediation_guidance": "Disable root SSH login in Junos:\n  set system services ssh root-login deny\n  set system services ssh protocol-version v2",
        "cis_mapping": "CIS Juniper Junos Benchmark 2.2.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-17, IA-2",
        "stig_mapping": "DISA STIG JUN-0120",
        "iso_mapping": "ISO 27001:2022 A.9.4.2"
    },

    # --- Logging & Auditing ---
    {
        "rule_code": "SEC-LOG-001",
        "title": "Centralized Remote Syslog Server",
        "category": "Logging",
        "vendor": "cisco",
        "default_severity": "HIGH",
        "description": "Configure at least one central remote syslog server for security audit trails.",
        "pass_pattern": r"logging host \d+\.\d+\.\d+\.\d+",
        "fail_pattern": r"no logging host",
        "remediation_guidance": "Configure remote syslog logging host:\n  (config)# logging host 10.100.1.50\n  (config)# logging trap informational",
        "cis_mapping": "CIS Cisco IOS Benchmark 3.1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-3, AU-6",
        "stig_mapping": "DISA STIG NET-0700",
        "iso_mapping": "ISO 27001:2022 A.12.4.1"
    },
    {
        "rule_code": "SEC-LOG-002",
        "title": "Millisecond Timestamping for Log Messages",
        "category": "Logging",
        "vendor": "cisco",
        "default_severity": "MEDIUM",
        "description": "Ensure log messages include high-precision datetime timestamps with timezone and msec precision.",
        "pass_pattern": r"service timestamps log datetime msec",
        "fail_pattern": r"(no service timestamps|service timestamps log uptime)",
        "remediation_guidance": "Enable detailed millisecond datetime log timestamps:\n  (config)# service timestamps log datetime msec show-timezone localtime",
        "cis_mapping": "CIS Cisco IOS Benchmark 3.1.2 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-8",
        "stig_mapping": "DISA STIG NET-0710",
        "iso_mapping": "ISO 27001:2022 A.12.4.4"
    },
    {
        "rule_code": "SEC-LOG-003",
        "title": "Junos Syslog Remote Collector",
        "category": "Logging",
        "vendor": "junos",
        "default_severity": "HIGH",
        "description": "Configure Junos system syslog host for security log archival.",
        "pass_pattern": r"system syslog host \d+\.\d+\.\d+\.\d+",
        "fail_pattern": r"no system syslog host",
        "remediation_guidance": "Set syslog host in Junos:\n  set system syslog host 10.100.1.50 any notice",
        "cis_mapping": "CIS Juniper Junos Benchmark 3.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-3",
        "stig_mapping": "DISA STIG JUN-0200",
        "iso_mapping": "ISO 27001:2022 A.12.4.1"
    },
    {
        "rule_code": "SEC-LOG-004",
        "title": "FortiOS Disk / FortiAnalyzer Logging",
        "category": "Logging",
        "vendor": "fortios",
        "default_severity": "HIGH",
        "description": "Enable event logging to disk or remote FortiAnalyzer/Syslog server.",
        "pass_pattern": r"(set status enable|config log syslogd setting)",
        "fail_pattern": r"set status disable",
        "remediation_guidance": "Enable syslogd setting in FortiOS:\n  config log syslogd setting\n    set status enable\n    set server 10.100.1.50\n  end",
        "cis_mapping": "CIS Fortinet FortiOS Benchmark 3.2 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-2",
        "stig_mapping": "DISA STIG FGT-0110",
        "iso_mapping": "ISO 27001:2022 A.12.4.1"
    },

    # --- SNMP & Management ---
    {
        "rule_code": "SEC-SNMP-001",
        "title": "Disable Default SNMP Community Strings",
        "category": "SNMP",
        "vendor": "cisco",
        "default_severity": "CRITICAL",
        "description": "Remove default public or private SNMP community strings.",
        "pass_pattern": r"no snmp-server community (public|private)",
        "fail_pattern": r"snmp-server community (public|private)",
        "remediation_guidance": "Remove default SNMP communities:\n  (config)# no snmp-server community public\n  (config)# no snmp-server community private",
        "cis_mapping": "CIS Cisco IOS Benchmark 4.1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 IA-2, SC-7",
        "stig_mapping": "DISA STIG NET-0800",
        "iso_mapping": "ISO 27001:2022 A.13.1.3"
    },
    {
        "rule_code": "SEC-SNMP-002",
        "title": "Enforce SNMP v3 Security Group",
        "category": "SNMP",
        "vendor": "cisco",
        "default_severity": "HIGH",
        "description": "Ensure SNMP uses Version 3 with authPriv encryption (SHA + AES).",
        "pass_pattern": r"snmp-server group .* v3 priv",
        "fail_pattern": r"snmp-server group .* v1|snmp-server group .* v2c",
        "remediation_guidance": "Configure SNMPv3 with authPriv:\n  (config)# snmp-server group SECGROUP v3 priv\n  (config)# snmp-server user SECUSER SECGROUP v3 auth sha <auth-pass> priv aes 128 <priv-pass>",
        "cis_mapping": "CIS Cisco IOS Benchmark 4.1.2 (L1)",
        "nist_mapping": "NIST SP 800-53 SC-8, IA-2",
        "stig_mapping": "DISA STIG NET-0810",
        "iso_mapping": "ISO 27001:2022 A.13.2.1"
    },

    # --- NTP Synchronization ---
    {
        "rule_code": "SEC-NTP-001",
        "title": "NTP Server Synchronization & Authentication",
        "category": "NTP",
        "vendor": "cisco",
        "default_severity": "MEDIUM",
        "description": "Ensure network device synchronizes time with trusted NTP servers with authentication enabled.",
        "pass_pattern": r"ntp server \d+\.\d+\.\d+\.\d+",
        "fail_pattern": r"no ntp server",
        "remediation_guidance": "Configure authenticated NTP servers:\n  (config)# ntp authenticate\n  (config)# ntp server 10.100.1.1 key 1",
        "cis_mapping": "CIS Cisco IOS Benchmark 5.1.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-8(1)",
        "stig_mapping": "DISA STIG NET-0900",
        "iso_mapping": "ISO 27001:2022 A.12.4.4"
    },
    {
        "rule_code": "SEC-NTP-002",
        "title": "Junos NTP Server Configuration",
        "category": "NTP",
        "vendor": "junos",
        "default_severity": "MEDIUM",
        "description": "Ensure Junos system ntp server is defined.",
        "pass_pattern": r"system ntp server \d+\.\d+\.\d+\.\d+",
        "fail_pattern": r"no system ntp server",
        "remediation_guidance": "Configure NTP server in Junos:\n  set system ntp server 10.100.1.1",
        "cis_mapping": "CIS Juniper Junos Benchmark 5.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-8(1)",
        "stig_mapping": "DISA STIG JUN-0300",
        "iso_mapping": "ISO 27001:2022 A.12.4.4"
    },

    # --- Session & Admin Access ---
    {
        "rule_code": "SEC-ADM-001",
        "title": "VTY Exec Timeout Limit",
        "category": "Admin Access",
        "vendor": "cisco",
        "default_severity": "HIGH",
        "description": "Set exec-timeout on VTY lines to automatically disconnect idle admin sessions within 10 minutes.",
        "pass_pattern": r"exec-timeout (0?[1-9]|10) 0",
        "fail_pattern": r"exec-timeout 0 0",
        "remediation_guidance": "Set VTY exec timeout to 10 minutes or less:\n  (config)# line vty 0 15\n  (config-line)# exec-timeout 10 0",
        "cis_mapping": "CIS Cisco IOS Benchmark 1.3.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-12",
        "stig_mapping": "DISA STIG NET-0500",
        "iso_mapping": "ISO 27001:2022 A.11.2.9"
    },
    {
        "rule_code": "SEC-ADM-002",
        "title": "Login Unauthorized Access Warning Banner",
        "category": "Admin Access",
        "vendor": "cisco",
        "default_severity": "LOW",
        "description": "Display legal advisory warning banner upon terminal login.",
        "pass_pattern": r"banner (motd|login)",
        "fail_pattern": r"no banner (motd|login)",
        "remediation_guidance": "Configure legal warning banner:\n  (config)# banner motd # Authorized Access Only. All activities monitored. #",
        "cis_mapping": "CIS Cisco IOS Benchmark 1.4.1 (L1)",
        "nist_mapping": "NIST SP 800-53 AC-8",
        "stig_mapping": "DISA STIG NET-0510",
        "iso_mapping": "ISO 27001:2022 A.13.1.1"
    },

    # --- Firewall & ACL Security ---
    {
        "rule_code": "SEC-ACL-001",
        "title": "Explicit Deny and Logging on Access Lists",
        "category": "Firewall ACL",
        "vendor": "cisco",
        "default_severity": "HIGH",
        "description": "Ensure IP access lists include explicit deny any log at the end for security event monitoring.",
        "pass_pattern": r"deny ip any any log",
        "fail_pattern": r"permit ip any any",
        "remediation_guidance": "Append explicit log drop rule to ACL:\n  (config-ext-nacl)# deny ip any any log",
        "cis_mapping": "CIS Cisco IOS Benchmark 6.1.1 (L2)",
        "nist_mapping": "NIST SP 800-53 SC-7, AU-2",
        "stig_mapping": "DISA STIG NET-1000",
        "iso_mapping": "ISO 27001:2022 A.13.1.1"
    },
    {
        "rule_code": "SEC-ACL-002",
        "title": "FortiOS Implicit Policy Logging",
        "category": "Firewall ACL",
        "vendor": "fortios",
        "default_severity": "MEDIUM",
        "description": "Ensure default implicit deny policy logs all dropped traffic.",
        "pass_pattern": r"set logtraffic all",
        "fail_pattern": r"set logtraffic utm",
        "remediation_guidance": "Enable logtraffic all on firewall policy:\n  config firewall policy\n    edit 0\n      set logtraffic all\n  end",
        "cis_mapping": "CIS Fortinet FortiOS Benchmark 6.2 (L1)",
        "nist_mapping": "NIST SP 800-53 AU-2",
        "stig_mapping": "DISA STIG FGT-0200",
        "iso_mapping": "ISO 27001:2022 A.12.4.1"
    }
]
